import { APIError, createAuthEndpoint } from "better-auth/api";
import { setSessionCookie } from "better-auth/cookies";
import type { BetterAuthPlugin } from "better-auth";
import * as z from "zod";

/**
 * Body shape requested for `auth.api.signIn`: validated upstream (e.g. after your own API call).
 * Passwords must never be passed here.
 */
const signInBodySchema = z.object({
	user: z
		.object({
			id: z.union([z.string(), z.number()]),
			name: z.string().optional(),
			email: z.string().email().optional(),
			image: z.string().nullable().optional(),
			roles: z.array(z.string()).optional(),
		})
		.passthrough(),
	accessToken: z.string().min(1),
	provider: z.literal("external-api").default("external-api"),
});

export type ExternalSignInBody = z.infer<typeof signInBodySchema>;

function stripSensitive(obj: Record<string, unknown>): Record<string, unknown> {
	const next = { ...obj };
	for (const key of Object.keys(next)) {
		if (key.toLowerCase().includes("password")) delete next[key];
	}
	return next;
}

/**
 * Registers `POST /sign-in/external-session` exposed as `auth.api.signIn` on the server.
 * Creates or updates the in-memory user row, then issues a JWT-backed session cookie (see root auth config).
 */
export function externalSignInPlugin(): BetterAuthPlugin {
	return {
		id: "external-sign-in",
		endpoints: {
			signIn: createAuthEndpoint(
				"/sign-in/external-session",
				{
					method: "POST",
					operationId: "signIn",
					requireHeaders: true,
					metadata: {
						scope: "server",
					},
					body: signInBodySchema,
				},
				async (ctx) => {
					const { user: rawUser, accessToken, provider } = ctx.body;
					const externalId = String(rawUser.id);
					const email =
						typeof rawUser.email === "string" && rawUser.email.length > 0
							? rawUser.email.toLowerCase()
							: `${externalId}@external.local`;

					const roles = Array.isArray(rawUser.roles) ? rawUser.roles : [];
					const safeProfile = stripSensitive(rawUser as Record<string, unknown>);
					const externalUserJson = JSON.stringify(safeProfile);

					const existing = await ctx.context.internalAdapter.findOAuthUser(
						email,
						externalId,
						"external-api",
					);

					let userRow;

					if (existing?.user) {
						userRow = await ctx.context.internalAdapter.updateUser(
							existing.user.id,
							{
								name: (rawUser.name as string | undefined) ?? existing.user.name ?? "",
								email,
								emailVerified: true,
								image: (rawUser.image as string | null | undefined) ?? existing.user.image ?? null,
								externalAccessToken: accessToken,
								rolesJson: JSON.stringify(roles),
								externalUserJson,
								authProvider: provider,
							} as never,
						);

						const linked =
							existing.linkedAccount ??
							existing.accounts?.find(
								(a) => a.providerId === "external-api" && a.accountId === externalId,
							);
						if (linked) {
							await ctx.context.internalAdapter.updateAccount(linked.id, {
								accessToken,
							});
						}
					} else {
						// User `id` is generated by Better Auth; the upstream id stays in `account.accountId` and `externalUserJson`.
						const created = await ctx.context.internalAdapter.createOAuthUser(
							{
								name: (rawUser.name as string | undefined) ?? "",
								email,
								emailVerified: true,
								image: (rawUser.image as string | null | undefined) ?? null,
								externalAccessToken: accessToken,
								rolesJson: JSON.stringify(roles),
								externalUserJson,
								authProvider: provider,
							} as never,
							{
								providerId: "external-api",
								accountId: externalId,
								accessToken,
							},
						);
						userRow = created.user;
					}

					if (!userRow) {
						throw APIError.from("INTERNAL_SERVER_ERROR", {
							code: "USER_PERSIST_FAILED",
							message: "Could not persist user session",
						});
					}

					const session = await ctx.context.internalAdapter.createSession(userRow.id, false);
					if (!session) {
						throw APIError.from("INTERNAL_SERVER_ERROR", {
							code: "SESSION_CREATE_FAILED",
							message: "Could not create session",
						});
					}

					await setSessionCookie(ctx, { session, user: userRow }, false);

					return ctx.json({
						ok: true,
						user: {
							id: userRow.id,
							email: userRow.email,
							name: userRow.name,
							image: userRow.image,
						},
					});
				},
			),
		},
	};
}
